apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secret
  namespace: task-manager
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: ""
  JWT_SECRET: BNFyT0X+HR0x4GMCXZ4YcYCPdCA/A0TbuIMwkaXAUDI=

